name: Smoke Test (run code & image)

on:
  workflow_dispatch:         
  push:
    branches: [ "main" ]   

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      # 1) Trae tu código
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Prepara Node y dependencias 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # 3) Smoke Test: ejecutar tu app mínimamente y mostrar un log
      - name: Run Smoke Test (code)
        run: |
          node -e "require('./app'); console.log('✅ Smoke: App arrancó correctamente')"

    

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: janem23
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest image
        run: docker pull janem23/image:latest

      
      - name: Run container (demo log)
        run: |
          docker run --rm janem23/image:latest node -e "console.log('✅ Smoke: Contenedor ejecutado OK')"
